profile: default
name: sfc_helper
version: 2.0
config-version: 2

require-dbt-version: ">=0.15.0"

target-path: target
clean-targets: ["target", "dbt_modules"]
macro-paths: ["macros"]
model-paths: ["models"]
